#!/usr/bin/env python
import logging
import os
import os.path
__author__ = 'mca18'
from argh import *
import namespaces

LOG = logging.getLogger('namespaces')
LOG.setLevel(logging.INFO)
THIS_DIR = os.path.dirname(os.path.realpath(__file__))


@dispatch_command
@arg('host', help='Which host should we look up the namespace for')
def ns(**kwargs):
    try:
        host_ns_list = namespaces.get_namespaces(kwargs['host'])
        for host in host_ns_list:
            print str(host)
    except namespaces.RegionError as error:
        LOG.error(error.message)

